Types and variables
Alvis257/C-sharp-syllabus-learn pull request #1
Opened 2021-11-24 19:15 UTC by Alvis257

2021-11-24 20:24 UTC, ausmoons requested changes

2021-11-24 20:24 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            //fixme - should be 15.5 :|
lieks komentārs

2021-11-24 20:24 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Excersise_8/Program.cs
> +            int Minutes,Days, Years, MinutesInAYear,RemeiningMinutes, MinutesInADay;
Šos deklarē ar mazo burtu

2021-11-24 20:24 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Excersise_8/Program.cs
> +            int Minutes,Days, Years, MinutesInAYear,RemeiningMinutes, MinutesInADay;
Izlabo arī visās citās vietās

2021-11-24 20:24 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/SadFor/Program.cs
>              //fixme so I would compile
Lieks komentārs. Pārskati visus failus

2021-11-25 17:01 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/SadFor/Program.cs
>              //fixme so I would compile
Neredzu, ka šis būtu izņemts

2021-11-26 10:47 UTC, EdgarsSalmins approved these changes
komentāri ir izlaboti.

2021-11-26 11:54 UTC, merged