Aritmetics
Alvis257/C-sharp-syllabus-learn pull request #2
Opened 2021-11-26 21:26 UTC by Alvis257

2021-11-27 14:24 UTC, ausmoons requested changes

2021-11-27 14:24 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Excersise_1/Program.cs
> +                answer = true;
Vienādās darbības var likt zem viena if

2021-11-27 14:24 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise_5/Program.cs
> +            {
Šis var būt kā else, jo citas iespējas vairs nav

2021-11-27 14:24 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise_9/Program.cs
> +                Console.WriteLine("Youre BMI is " + Math.Round(bMI, 2)
Kur būs 18.5 un 25?

2021-11-27 17:09 UTC, Alvis257 commented on csharp-basics/exercises/Arithmetic/Exercise_9/Program.cs
> +                Console.WriteLine("Youre BMI is " + Math.Round(bMI, 2)
Šeit arī viņi aizies.

2021-11-28 19:26 UTC, ausmoons approved these changes

2021-11-28 21:55 UTC, merged