Classes and objects
Alvis257/C-sharp-syllabus-learn pull request #6
Opened 2021-12-09 09:48 UTC by Alvis257

2021-12-09 20:35 UTC, ausmoons requested changes

2021-12-09 20:35 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        private string _name { get; set; }
Private neiet kopā ar { get; set; }

2021-12-09 20:35 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Product.cs
> +
Lieka tukša rinda

2021-12-09 20:35 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise1/Product.cs
> +        public double[] _priceAtStart { get; set; }
Izskatās, ka šiem ir jābū kā private un virs konstruktora, bez get; set

2021-12-09 20:35 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/FuelGauge.cs
> +        public bool _full = false;
Tiešām jābūt public?

2021-12-09 20:35 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/FuelGauge.cs
> +        public void addFuel()
Metodes ar lielo burtu

2021-12-09 20:35 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/FuelGauge.cs
> +                _currentLiters -= 1;
Šis ir arī iepriekš

2021-12-09 20:35 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/Program.cs
> +                if (!fuel._full)
isFull. Public ir bez _

2021-12-09 20:35 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise4/Movie.cs
> +        public string _raiting { get; private set; }
Namings nav pareizs un lieka tukša rinda

2021-12-12 00:09 UTC, Alvis257 commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/Program.cs
> +                if (!fuel._full)
Ar, jo tiek tā definēta lai neizmantotu (this), tas tikai tādēļ ka man nav metodes isFull man tiek parbaudīts pašā AddFull metode un ar to man ir public bool _full.

2021-12-12 00:10 UTC, Alvis257 commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/FuelGauge.cs
> +        public bool _full = false;
Ja, jo es izmantoju viņus mainā citadi man vajadzētu taisīt metodes kas ļaus piekļūt pie viņām tāpēc vienkāršāk izmantot public šajā uzdevumā.

2021-12-12 17:24 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/FuelGauge.cs
> +        public bool _full = false;
Tad CurrentLiters un IsFull

2021-12-12 17:28 UTC, ausmoons requested changes

2021-12-12 17:28 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/Program.cs
> +                if (!fuel._full)
Tad veic pārbaudi AddFuel metodē, nevis šeit

2021-12-17 20:01 UTC, ausmoons requested changes

2021-12-17 20:01 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise3/FuelGauge.cs
> +        public bool IsFullOrEmpty()
IsFullOrEmpty - true/ yes. Ko tev tas pasaka? Vai nu isFull vai isEmty. Te nav saprotams, ko šis bool pasaka

2021-12-19 21:42 UTC, ausmoons approved these changes

2021-12-20 00:01 UTC, merged